// commonActions — tiered curated sets of the most common/essential commands per editor,
// used for cheatsheet filtering, sidebar ordering, and export prioritization.
// TIER1: 30–50 most-used shortcuts; TIER2: next 20–50 somewhat-common shortcuts.
import type { Editor } from './editor-formats';

export const TIER1_ACTIONS: Record<Editor, Set<string>> = {
  vscode: new Set([
    'undo',
    'redo',
    'selectAll',
    'editor.action.clipboardCopyAction',
    'editor.action.clipboardCutAction',
    'editor.action.clipboardPasteAction',
    'editor.action.deleteLines',
    'editor.action.commentLine',
    'editor.action.formatDocument',
    'editor.action.find',
    'editor.action.startFindReplaceAction',
    'editor.action.nextMatchFindAction',
    'editor.action.previousMatchFindAction',
    'editor.action.revealDefinition',
    'editor.action.goToImplementation',
    'editor.action.rename',
    'editor.action.quickFix',
    'editor.action.triggerSuggest',
    'editor.action.addCursorAbove',
    'editor.action.addCursorBelow',
    'editor.action.addSelectionToNextFindMatch',
    'editor.action.selectHighlights',
    'editor.action.moveLineUp',
    'editor.action.moveLineDown',
    'editor.action.indentLines',
    'editor.action.outdentLines',
    'editor.action.fold',
    'editor.action.unfold',
    'editor.action.foldAll',
    'editor.action.unfoldAll',
    'editor.action.marker.next',
    'editor.action.marker.prev',
    'workbench.action.files.save',
    'workbench.action.files.newUntitledFile',
    'workbench.action.quickOpen',
    'workbench.action.showCommands',
    'workbench.action.closeActiveEditor',
    'workbench.action.reopenClosedEditor',
    'workbench.action.splitEditor',
    'workbench.action.toggleSidebarVisibility',
    'workbench.action.terminal.toggleTerminal',
    'workbench.action.debug.start',
    'workbench.action.navigateBack',
    'workbench.action.navigateForward',
    'workbench.action.openSettings',
    'editor.debug.action.toggleBreakpoint',
  ]),

  jetbrains: new Set([
    '$Undo',
    '$Redo',
    '$Copy',
    '$Cut',
    '$Paste',
    '$SelectAll',
    'SaveAll',
    'ReformatCode',
    'OptimizeImports',
    'ToggleLineComment',
    'Find',
    'FindInPath',
    'Replace',
    'ReplaceInPath',
    'FindUsages',
    'FindNext',
    'FindPrevious',
    'SearchEverywhere',
    'GotoDeclaration',
    'GotoImplementation',
    'GotoClass',
    'GotoFile',
    'GotoAction',
    'GotoNextError',
    'GotoPreviousError',
    'RenameElement',
    'ShowIntentionActions',
    'CodeCompletion',
    'ExtractMethod',
    'ExtractVariable',
    'FileStructurePopup',
    'Run',
    'Debug',
    'ToggleLineBreakpoint',
    'StepOver',
    'StepInto',
    'StepOut',
    'Resume',
    'EditorDeleteLine',
    'EditorDuplicate',
    'EditorMoveStatementUp',
    'EditorMoveStatementDown',
    'EditorAddCaretBelow',
    'EditorAddCaretAbove',
    'EditorSelectAllOccurrences',
    'CloseContent',
    'ActivateTerminalToolWindow',
    'Back',
    'Forward',
    'ShowSettings',
  ]),

  vim: new Set([
    'i',
    'a',
    'o',
    'O',
    'Escape',
    'u',
    'Ctrl+r',
    '.',
    'y',
    'yy',
    'd',
    'dd',
    'D',
    'x',
    'p',
    'P',
    'v',
    'V',
    'Ctrl+v',
    '/',
    '?',
    'n',
    'N',
    '*',
    ':%s',
    'gg',
    'G',
    'w',
    'b',
    'e',
    '0',
    '$',
    '%',
    'Ctrl+f',
    'Ctrl+b',
    'Ctrl+d',
    'Ctrl+u',
    ':w',
    ':q',
    ':wq',
    ':q!',
    'ZZ',
    'gd',
    'K',
    'Ctrl+]',
    'Ctrl+o',
    'Ctrl+i',
    'zz',
    '>>',
    '<<',
  ]),

  neovim: new Set([
    'i',
    'a',
    'o',
    'O',
    'Escape',
    'u',
    'Ctrl+r',
    '.',
    'y',
    'yy',
    'd',
    'dd',
    'D',
    'x',
    'p',
    'P',
    'v',
    'V',
    'Ctrl+v',
    '/',
    '?',
    'n',
    'N',
    '*',
    ':%s',
    'gg',
    'G',
    'w',
    'b',
    'e',
    '0',
    '$',
    '%',
    'Ctrl+f',
    'Ctrl+b',
    'Ctrl+d',
    'Ctrl+u',
    ':w',
    ':q',
    ':wq',
    ':q!',
    'ZZ',
    'gd',
    'K',
    'Ctrl+]',
    'Ctrl+o',
    'Ctrl+i',
    'zz',
    '>>',
    '<<',
  ]),

  zed: new Set([
    'editor::Undo',
    'editor::Redo',
    'editor::SelectAll',
    'editor::Copy',
    'editor::Cut',
    'editor::Paste',
    'editor::DeleteLine',
    'editor::DuplicateLine',
    'editor::ToggleComments',
    'editor::Format',
    'editor::Find',
    'editor::FindAndReplace',
    'editor::SelectNextMatch',
    'editor::SelectPreviousMatch',
    'editor::SelectAllMatches',
    'editor::GoToDefinition',
    'editor::GoToTypeDefinition',
    'editor::GoToImplementation',
    'editor::FindReferences',
    'editor::Rename',
    'editor::CodeActions',
    'editor::ShowCompletions',
    'editor::AddSelectionAbove',
    'editor::AddSelectionBelow',
    'editor::MoveLineUp',
    'editor::MoveLineDown',
    'editor::Fold',
    'editor::FoldAll',
    'editor::UnfoldAll',
    'editor::GoToDiagnostic',
    'editor::GoToPrevDiagnostic',
    'editor::Hover',
    'workspace::Save',
    'workspace::SaveAll',
    'workspace::CloseActiveItem',
    'workspace::ReopenClosedItem',
    'workspace::SplitRight',
    'zed::OpenFile',
    'zed::NewFile',
    'zed::OpenRecent',
    'zed::ToggleSidebar',
    'zed::ToggleTerminal',
    'zed::ToggleCommandPalette',
    'zed::FindInProject',
    'zed::OpenSettings',
    'pane::ActivateNextItem',
    'pane::ActivatePreviousItem',
    'project_panel::ToggleFocus',
  ]),

  emacs: new Set([
    'undo',
    'redo',
    'kill-region',
    'kill-ring-save',
    'yank',
    'yank-pop',
    'mark-whole-buffer',
    'set-mark-command',
    'save-buffer',
    'find-file',
    'kill-buffer',
    'switch-to-buffer',
    'execute-extended-command',
    'isearch-forward',
    'isearch-backward',
    'query-replace',
    'query-replace-regexp',
    'occur',
    'xref-find-definitions',
    'xref-find-references',
    'xref-go-back',
    'xref-go-forward',
    'other-window',
    'delete-window',
    'delete-other-windows',
    'split-window-right',
    'split-window-below',
    'keyboard-quit',
    'beginning-of-line',
    'end-of-line',
    'beginning-of-buffer',
    'end-of-buffer',
    'kill-line',
    'indent-for-tab-command',
    'indent-region',
    'comment-region',
    'goto-line',
    'recenter-top-bottom',
    'scroll-up-command',
    'scroll-down-command',
    'compile',
    'next-error',
    'previous-error',
    'eshell',
    'ibuffer',
  ]),

  krita: new Set([
    'edit_undo',
    'edit_redo',
    'edit_copy',
    'edit_cut',
    'edit_paste',
    'select_all',
    'deselect',
    'file_new',
    'file_open',
    'file_save',
    'file_save_as',
    'duplicatelayer',
    'merge_layer',
    'add_new_paint_layer',
    'remove_layer',
    'KritaShape/KisToolBrush',
    'KritaTransform/KisToolMove',
    'KritaFill/KisToolFill',
    'KritaFill/KisToolGradient',
    'KritaSelected/KisToolColorSampler',
    'mirror_canvas',
    'view_show_canvas_only',
    'view_zoom_in',
    'view_zoom_out',
    'zoom_to_100pct',
    'toggle_fg_bg',
  ]),

  illustrator: new Set([
    'Selection',
    'Direct Selection',
    'Pen',
    'Type',
    'Zoom',
    'Hand',
    'Toggle Fill/Stroke',
    'Default',
    'New',
    'Open',
    'Save',
    'Save As',
    'Print',
    'Undo',
    'Redo',
    'Cut',
    'Copy',
    'Paste',
    'Group',
    'Ungroup',
    'Bring to Front',
    'Send to Back',
    'Show Rulers',
    'Hide Guides',
    'Show Grid',
    'Zoom In',
    'Zoom Out',
    'Fit Artboard in Window',
    'Actual Size',
  ]),

  blender: new Set([
    'wm.search_menu',
    'wm.open_mainfile',
    'wm.save_mainfile',
    'wm.save_as_mainfile',
    'ed.undo',
    'ed.redo',
    'view3d.rotate',
    'view3d.move',
    'view3d.zoom',
    'view3d.view_all',
    'view3d.view_selected',
    'transform.rotate',
    'transform.translate',
    'transform.resize',
    'object.select_all',
    'object.delete',
    'mesh.select_all',
    'mesh.extrude_region_move',
  ]),
};

export const TIER2_ACTIONS: Record<Editor, Set<string>> = {
  vscode: new Set([
    'editor.action.blockComment',
    'editor.action.formatSelection',
    'editor.action.peekDefinition',
    'editor.action.goToTypeDefinition',
    'editor.action.refactor',
    'editor.action.sourceAction',
    'editor.action.triggerParameterHints',
    'editor.action.showHover',
    'editor.action.copyLinesUpAction',
    'editor.action.copyLinesDownAction',
    'editor.action.smartSelect.expand',
    'editor.action.smartSelect.shrink',
    'editor.action.jumpToBracket',
    'editor.action.insertLineBefore',
    'editor.action.insertLineAfter',
    'editor.action.gotoLine',
    'editor.action.gotoSymbol',
    'deleteWordLeft',
    'deleteWordRight',
    'cursorWordLeft',
    'cursorWordRight',
    'cursorTop',
    'cursorBottom',
    'cursorPageUp',
    'cursorPageDown',
    'workbench.action.files.saveAs',
    'workbench.action.saveAll',
    'workbench.action.files.openFile',
    'workbench.action.openRecent',
    'workbench.action.showAllSymbols',
    'workbench.action.gotoLine',
    'workbench.action.splitEditorRight',
    'workbench.action.splitEditorDown',
    'workbench.action.closeAllEditors',
    'workbench.action.openNextEditor',
    'workbench.action.openPreviousEditor',
    'workbench.action.terminal.new',
    'workbench.action.debug.stop',
    'workbench.action.debug.stepOver',
    'workbench.action.debug.stepInto',
    'workbench.action.debug.stepOut',
    'workbench.action.debug.continue',
    'workbench.action.zoomIn',
    'workbench.action.zoomOut',
    'workbench.action.togglePanel',
    'workbench.action.openKeyboardShortcuts',
    'git.commit',
    'git.push',
    'git.pull',
  ]),

  jetbrains: new Set([
    'ToggleBlockComment',
    'EditorFoldRegion',
    'EditorUnfoldRegion',
    'CollapseAll',
    'ExpandAll',
    'SmartTypeCompletion',
    'CompleteStatement',
    'ParameterInfo',
    'QuickJavaDoc',
    'QuickImplementations',
    'ShowErrorDescription',
    'GotoLine',
    'GotoSuperMethod',
    'GotoTest',
    'GotoSymbol',
    'RecentFiles',
    'RecentLocations',
    'Switcher',
    'PreviousTab',
    'NextTab',
    'SplitVertically',
    'SplitHorizontally',
    'CloseAllEditors',
    'ReopenClosedTab',
    'EditorSelectWord',
    'IndentSelection',
    'UnindentSelection',
    'ChangeSignature',
    'InlineMethod',
    'Compile',
    'Make',
    'Stop',
    'Rerun',
    'StepOver',
    'RunToCursor',
    'EvaluateExpression',
    'ToggleLineBreakpoint',
    'ViewBreakpoints',
    'CheckinProject',
    'Vcs.Push',
    'Git.Pull',
    'Annotate',
    'VcsShowLog',
    'ShowKeymap',
    'ActivateProjectToolWindow',
    'ActivateRunToolWindow',
    'ActivateDebugToolWindow',
    'ActivateVersionControlToolWindow',
    'ActivateProblemViewPanel',
  ]),

  vim: new Set([
    'I',
    'A',
    'cc',
    'C',
    'r',
    'R',
    's',
    'ciw',
    'cw',
    'diw',
    'dw',
    'yiw',
    'yw',
    'gv',
    '#',
    'f',
    'F',
    't',
    'T',
    ';',
    ',',
    '{',
    '}',
    'H',
    'M',
    'L',
    '^',
    'J',
    'gd',
    'gD',
    '==',
    'zR',
    'zM',
    'zo',
    'zc',
    'za',
    'm',
    'q',
    '@',
    'Ctrl+w h',
    'Ctrl+w j',
    'Ctrl+w k',
    'Ctrl+w l',
    'Ctrl+w s',
    'Ctrl+w v',
    'Ctrl+p',
    'Ctrl+n',
    ':bn',
    ':bp',
    ':bd',
  ]),

  neovim: new Set([
    'I',
    'A',
    'cc',
    'C',
    'r',
    'R',
    's',
    'ciw',
    'cw',
    'diw',
    'dw',
    'yiw',
    'yw',
    'gv',
    '#',
    'f',
    'F',
    't',
    'T',
    ';',
    ',',
    '{',
    '}',
    'H',
    'M',
    'L',
    '^',
    'J',
    'gd',
    'gD',
    '==',
    'zR',
    'zM',
    'zo',
    'zc',
    'za',
    'm',
    'q',
    '@',
    'Ctrl+w h',
    'Ctrl+w j',
    'Ctrl+w k',
    'Ctrl+w l',
    'Ctrl+w s',
    'Ctrl+w v',
    'Ctrl+p',
    'Ctrl+n',
    ':bn',
    ':bp',
    ':bd',
  ]),

  zed: new Set([
    'editor::SelectLine',
    'editor::Indent',
    'editor::Outdent',
    'editor::MoveToBeginningOfLine',
    'editor::MoveToEndOfLine',
    'editor::MoveToBeginning',
    'editor::MoveToEnd',
    'editor::MoveWordLeft',
    'editor::MoveWordRight',
    'editor::SelectWordLeft',
    'editor::SelectWordRight',
    'editor::DeleteWordBackward',
    'editor::DeleteWordForward',
    'editor::DeleteToBeginningOfLine',
    'editor::DeleteToEndOfLine',
    'editor::NewlineAbove',
    'editor::NewlineBelow',
    'editor::GoToLine',
    'editor::MovePageUp',
    'editor::MovePageDown',
    'editor::ScrollCursorCenter',
    'editor::ToggleFold',
    'editor::RevealInProjectPanel',
    'editor::FormatSelection',
    'workspace::SplitDown',
    'workspace::ActivateNextPane',
    'workspace::ActivatePreviousPane',
    'workspace::NewTerminal',
    'workspace::CloseAllItems',
    'pane::SplitRight',
    'pane::SplitDown',
    'outline_panel::ToggleFocus',
    'git_panel::ToggleFocus',
    'git_panel::StageFile',
    'git_panel::StageAll',
    'git_panel::Commit',
    'terminal::Clear',
    'zed::ToggleFileFinder',
    'zed::NewWindow',
    'zed::ToggleFullScreen',
    'project_panel::NewFile',
    'project_panel::RenameFile',
    'project_panel::DeleteFile',
    'assistant::InlineAssist',
  ]),

  emacs: new Set([
    'save-some-buffers',
    'write-file',
    'find-file-other-window',
    'revert-buffer',
    'list-buffers',
    'forward-word',
    'backward-word',
    'forward-paragraph',
    'backward-paragraph',
    'forward-sexp',
    'backward-sexp',
    'kill-word',
    'backward-kill-word',
    'delete-char',
    'backward-delete-char',
    'delete-horizontal-space',
    'open-line',
    'exchange-point-and-mark',
    'uncomment-region',
    'fill-paragraph',
    'transpose-chars',
    'transpose-words',
    'upcase-word',
    'downcase-word',
    'capitalize-word',
    'imenu',
    'describe-function',
    'describe-key',
    'apropos',
    'company-complete',
    'bookmark-set',
    'bookmark-jump',
    'kmacro-start-macro-or-insert-counter',
    'kmacro-end-or-call-macro',
    'balance-windows',
    'make-frame-command',
    'org-agenda',
    'org-capture',
    'magit-status',
    'projectile-find-file',
    'eglot-rename',
    'eglot-code-actions',
    'lsp-find-definition',
    'flycheck-next-error',
    'flycheck-previous-error',
  ]),

  krita: new Set([
    'create_quick_group',
    'create_quick_clipping_group',
    'quick_ungroup',
    'flatten_image',
    'activateNextLayer',
    'activatePreviousLayer',
    'move_layer_up',
    'move_layer_down',
    'toggle_layer_visibility',
    'toggle_layer_lock',
    'toggle_layer_alpha_lock',
    'toggle_layer_inherit_alpha',
    'rotate_canvas_left',
    'rotate_canvas_right',
    'reset_canvas_rotation',
    'toggle_zoom_to_fit',
    'zoom_to_fit',
    'help_contents',
    'show_brush_editor',
    'show_brush_presets',
    'show_color_selector',
    'show_tool_options',
    'toggle_display_selection',
    'invert_selection',
    'featherselection',
    'fill_selection_foreground_color',
    'fill_selection_background_color',
  ]),

  illustrator: new Set([
    'Place',
    'Export for Screens',
    'Preferences',
    'Keyboard Shortcuts',
    'Transform Again',
    'Align',
    'Clipping Mask Make',
    'Compound Path Make',
    'Create Outlines',
    'Make Pixel Perfect',
    'Find/Replace Font',
    'Preview',
    'GPU Preview',
    'Outline',
    'Show/Hide All Palettes',
    'Show/Hide All But Toolbox',
    'Layers',
    'Info',
    'Character',
    'Paragraph',
    'Pathfinder',
    'Transparency',
    'Appearance',
    'Document Info',
    'Graph',
  ]),

  blender: new Set([
    'screen.repeat_last',
    'screen.redo_last',
    'screen.screen_full_area',
    'view3d.cursor3d',
    'view3d.view_camera',
    'view3d.localview',
    'view3d.toggle_xray',
    'view3d.zoom_border',
    'object.duplicate_move',
    'object.duplicate_move_linked',
    'object.mode_set',
    'mesh.bevel',
    'mesh.loopcut_slide',
    'mesh.inset',
    'mesh.knife_tool',
    'node.select_all',
    'graph.select_all',
    'text.paste',
    'text.duplicate_line',
    'text.line_break',
  ]),
};

export function getActionTier(editor: Editor, command: string): 1 | 2 | null {
  if (TIER1_ACTIONS[editor]?.has(command)) return 1;
  if (TIER2_ACTIONS[editor]?.has(command)) return 2;
  return null;
}

export const COMMON_ACTIONS: Record<Editor, Set<string>> = Object.fromEntries(
  (Object.keys(TIER1_ACTIONS) as Editor[]).map((editor) => [
    editor,
    new Set([...TIER1_ACTIONS[editor], ...TIER2_ACTIONS[editor]]),
  ])
) as Record<Editor, Set<string>>;

export function isCommonAction(editor: Editor, command: string): boolean {
  return getActionTier(editor, command) !== null;
}
